name: Workflow 1

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for lock file
        shell: pwsh
        run: |
          if [ -f lock ]; then
            echo "Lock file found, waiting for it to be released."
            ls -ltr
            pwd
            exit 1
          else
            echo "No lock file found, proceeding."
            touch lock
            ls -ltr
            pwd
          fi
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        shell: pwsh
        run: |
         echo "This is Workflow 1 - Job 1"
         Start-Sleep -s 20

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        shell: pwsh
        run: echo "This is Workflow 1 - Job 2"

      - name: Remove lock file
        run: rm lock
        
