# name: Workflow-1

# on:
#   workflow_dispatch:  

# jobs:
#   example-job1:
#     runs-on: self-hosted
#     steps:
#       - name: Acquire lock
#         id: acquire-lock
#         run: |
#           LOCK_FILE=/tmp/workflow.lock
#           while [ -f $LOCK_FILE ]; do
#             echo "Another workflow running. waiting..."
#             sleep 10
#           done
#           touch $LOCK_FILE
#       - name: Step 1
#         run: |
#          echo "This is Workflow 1 - Step 1"
#          cat /proc/sys/kernel/hostname
#          sleep 60
#       - name: Release lock
#         if: always()
#         run: |
#           LOCK_FILE=/tmp/workflow.lock
#           rm -f $LOCK_FILE

#############multiple jobs###########

name: Workflow 1

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: runner1
    # needs: lock_job
    steps:
      - name: Step 1
        run: |
          echo "This is Workflow 1 - Job 1"
         # Start-Sleep -Seconds 10

  job2:
    runs-on: runner2
#    needs: [job1]
    steps:
      - name: Step 2
        run: |
          echo "This is Workflow 1 - Job 2"
      #    Start-Sleep -Seconds 10

 #  job3:
 #    runs-on: self-hosted
 # #   needs: [job1]
 #    steps:   
 #      - name: Step 3
 #        run: |
 #          echo "This is Workflow 1 - Job 3"
 #       #   Start-Sleep -Seconds 20

 #  job4:
 #    runs-on: self-hosted
 # #   needs: [job1]
 #    steps:     
 #      - name: Step 4
 #        run: echo "This is Workflow 1 - Job 4"




