name: Workflow 1

on:
  workflow_dispatch:  
#  pus    
 

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false
# concurrency: 
#   group: ${{ github.head_ref ||  github.ref }}

jobs:
  job1:
    runs-on: self-hosted, runner1
    
    steps:
      - name: Step 1
        run: |
         echo "This is Workflow 1 - Job 1"
         sleep 30 

  job2:
    runs-on: self-hosted, runner1
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is Workflow 1 - Job 2"
        
        


  


