name: Workflow 3

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: runner1
    # needs: lock_job
    steps:
      - name: Check if lock file exists
        run: |
          if [ -f /path/to/lockfile ]; then
            echo "Lock file exists. Exiting."
            exit 1
          fi
      - name: Create lock file
        run: touch /path/to/lockfile
          
      - name: Step 1
        run: |
          echo "This is Workflow 3 - Job 1"
      
          

  job2:
    runs-on: runner2
#    needs: [job1]
    steps:
      - name: Step 2
        run: |
          echo "This is Workflow 3 - Job 2"
          

  job3:
    runs-on: runner3
  #  needs: [job1]
    steps:   
      - name: Step 3
        run: |
          echo "This is Workflow 3 - Job 3"

      - name: Release lock
        if: always()
        run: |
          LOCK_FILE=/tmp/workflow.lock
          rm -f $LOCK_FILE

      - name: Remove lock file
        run: rm /path/to/lockfile
          

  # job4:
  #   runs-on: runner4
  # #  needs: [job1]
  #   steps:   
  #     - name: Step 3
  #       run: |
  #         echo "This is Workflow 1 - Job 3"
  #      #   Sleep 20
