name: Workflow 1

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: runner1
    steps:
      - name: Step 1
        run: |
          echo "This is Workflow 1 - Job 1"      

  job2:
    runs-on: runner1
#    needs: [job1]
    steps:
      - name: Step 2
        run: |
          echo "This is Workflow 1 - Job 2"
          sleep 10
          

  job3:
    runs-on: runner1
 #   needs: [job2]
    steps:   
      - name: Step 3
        run: |
          echo "This is Workflow 1 - Job 3"
          sleep 10
          

  job4:
    runs-on: runner1
 #   needs: [job3]
    steps:   
      - name: Step 3
        run: |
          echo "This is Workflow 1 - Job 3"
        
      




