name: Workflow-5

on:
  workflow_dispatch:  

jobs:
  exampple-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
         echo "This is Workflow 1 - Job 1"
         sleep 10 
