name: Workflow 1

on:
  workflow_dispatch:  
  # push:\\\
  
 

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false

jobs:
  build:
    runs-on: self-hosted
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      # - name: Build application
      #   run: npm build

  test:
    runs-on: self-hosted
   # needs: build  # Wait for the 'build' job to complete
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      
      # - name: Install dependencies
      #   run: npm install
      
      - name: Run tests
        run: npm test

  deploy:
    runs-on: self-hosted
    # needs: [build, test]  # Wait for both 'build' and 'test' jobs to complete
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2
      
      - name: Deploy to production
        run: |
          echo "Deploying..."

# jobs:
#   job1:
#     runs-on: self-hosted
    
#     steps:
#       - name: Step 1
#         run: |
#          echo "This is Workflow 1 - Job 1"
#          sleep 10 

#   job2:
#     runs-on: self-hosted
#    # needs: job1
#     steps:
#       - name: Step 2
#         run: |
#          echo "This is Workflow 1 - Job 2"
#          sleep 10

#   job3:
#     runs-on: self-hosted
#    # needs: job2
#     steps:
#       - name: Step 3
#         run: echo "This is Workflow 1 - Job 3"

#   job4:
#     runs-on: self-hosted
#    # needs: job2
#     steps:
#       - name: Step 4
#         run: echo "This is Workflow 1 - Job 4"
        
        


  


