name: Workflow 2

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: runner1
    steps:
      - name: Acquire lock
        id: acquire-lock
        run: |
          LOCK_FILE=/tmp/workflow.lock
          while [ -f $LOCK_FILE ]; do
            echo "Another workflow running. waiting..."
            sleep 10
          done
          touch $LOCK_FILE
          
      - name: Step 1
        run: |
          echo "This is Workflow 2 - Job 1"
          

  job2:
    runs-on: runner2
#    needs: [job1]
    steps:
      - name: Step 2
        run: |
          echo "This is Workflow 2 - Job 2"
          
  job3:
    runs-on: runner3
 #   needs: [job1]
    steps:   
      - name: Step 3
        run: |
          echo "This is Workflow 2 - Job 3"
          

  job4:
    runs-on: runner4
 #   needs: [job1]
    steps:     
      - name: Step 4
        run: echo "This is Workflow 2 - Job 4"
      - name: Release lock
        if: always()
        run: |
          LOCK_FILE=/tmp/workflow.lock
          rm -f $LOCK_FILE
