name: Workflow 2

on:
  workflow_dispatch:
      
  pull_request:
 

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false

jobs:
  job1:
    runs-on: runner1
    steps:
      - name: Step 1
        run: |
         echo "This is Workflow 2 - Job 1"
          sleep 30 
  job2:
    runs-on: test1
#    needs: job1
    steps:
      - name: Step 1
        run: echo "This is Workflow 2 - Job 2"




