name: Workflow 2

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check Lock
        id: check-lock
        run: |
          echo "Checking lock status"
          if [ -f lock.txt ]; then
            echo "Another workflow is running. Waiting for lock to be released."
            exit 1
          fi
      - name: Step 1
        run: echo "This is Workflow 2 - Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is Workflow 2 - Job 2"
