# name: Workflow 2

# on:
#   workflow_dispatch:
      
#   pull_request:
 

# concurrency:
#   group: ci_workflow_group
#   cancel-in-progress: false

# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Step 1
#         run: |
#          echo "This is Workflow 2 - Job 1"
#           sleep 30 
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - name: Step 1
#         run: echo "This is Workflow 2 - Job 2"

name: Workflow 2

on:
  workflow_dispatch:

jobs:
  lock_job:
    runs-on: self-hosted
    outputs:
      lock_acquired: ${{ steps.lock_status.outputs.lock_acquired }}
    steps:
      - name: Acquire lock
        id: lock_status
        run: |
          $lockFile = "C:\Temp\workflow.lock"
          while (Test-Path $lockFile) {
            echo "Another workflow is running. Waiting..."
            Start-Sleep -Seconds 10
          }
          New-Item -ItemType File -Path $lockFile
          echo "Lock acquired."
          echo "::set-output name=lock_acquired::true"

  job1:
    runs-on: self-hosted
    # needs: lock_job
    steps:
      - name: Step 1
        run: |
          echo "This is Workflow 2 - Job 1"
          Start-Sleep -Seconds 10

  job2:
    runs-on: self-hosted
    needs: [job1]
    steps:
      - name: Step 2
        run: |
          echo "This is Workflow 2 - Job 2"
          Start-Sleep -Seconds 10

  job3:
    runs-on: self-hosted
    needs: [job1]
    steps:   
      - name: Step 3
        run: |
          echo "This is Workflow 2 - Job 3"
          Start-Sleep -Seconds 20

  job4:
    runs-on: self-hosted
    needs: [job1]
    steps:     
      - name: Step 4
        run: echo "This is Workflow 2 - Job 4"

  release_lock:
    runs-on: self-hosted
    # needs: [job4]
    if: always()
    steps:
      - name: Release lock
        run: |
          $lockFile = "C:\Temp\workflow.lock"
          Remove-Item -Path $lockFile

