name: Workflow 2

on:
  workflow_dispatch:
      
  pull_request:
  push:

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false

# concurrency: 
#   group: ${{ github.head_ref ||  github.ref }}

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: Step 1
        run: |
         echo "This is Workflow 2 - Job 1"
          sleep 30 
  job2:
    runs-on: self-hosted
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is Workflow 2 - Job 2"




