name: Workflow 1

on:
  workflow_dispatch:  
  # push:

concurrency:
  group: ci_workflow_group
  cancel-in-progress: false

jobs:
  job1:
    runs-on: parallel-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Step 1
        run: |
         echo "This is Workflow 1 - Job 1"
         sleep 10 

  job2:
    runs-on: self-hosted
   # needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Step 2
        run: |
         echo "This is Workflow 1 - Job 2"
         sleep 10

  job3:
    runs-on: ubuntu-latest
   # needs: job2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Step 3
        run: echo "This is Workflow 1 - Job 3"

  # job4:
  #   runs-on: self-hosted
  #  # needs: job3
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
        
  #     - name: Step 4
  #       run: echo "This is Workflow 1 - Job 4"
        
        


  


