name: ParallelExecution

on: [push]

jobs:
  job1:
    runs-on: runner1
    steps:
      - name: Job 1
        run: echo "Output from Job 1" > job1_output.txt
      - name: job1 output
        uses: actions/upload-artifact@v3
        with:
          name: job1-output
          path: job1_output.txt

  job2:
    runs-on: runner2
    steps:
      - name: Run Job 2
        run: echo "Output from Job 2" > job2_output.txt
      - name: Job2 Output
        uses: actions/upload-artifact@v3
        with:
          name: job2-output
          path: job2_output.txt

  job3:
    runs-on: runner1
    steps:
      - name: Download Job 1 Output
        uses: actions/download-artifact@v3
        with:
          name: job1-output
          path: ./job1_output
      - name: Wait for Job 1 Output
        shell: powershell
        run: |
          while (-Not (Test-Path -Path ./job1_output/job1_output.txt)) {
            Write-Host "Waiting for Job 1 output..."
            Start-Sleep -Seconds 10
          }
      - name: Run Job 3
        shell: powershell
        run: Get-Content ./job1_output/job1_output.txt

  job4:
    runs-on: runner2
    steps:
      - name: Download Job 2 Output
        uses: actions/download-artifact@v3
        with:
          name: job2-output
          path: ./job2_output
      - name: Wait for Job 2 Output
        shell: powershell
        run: |
          while (-Not (Test-Path -Path ./job2_output/job2_output.txt)) {
            Write-Host "Waiting for Job 2 output..."
            Start-Sleep -Seconds 10
          }
      - name: Run Job 5
        shell: powershell
        run: Get-Content ./job2_output/job2_output.txt

# name: GitHub Actions Parallel Run
# 'on':
#   workflow_dispatch: 
#   pull_request:
#   push:
      
    
# jobs:
#   Google-Test:
#     timeout-minutes: 120
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Google-Test
#         uses: cypress-io/github-action@v2
#         with:
#           command: npm run google
#           browser: chrome
#           headless: true
#           record: false
#   Amazon-Test:
#     timeout-minutes: 120
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Google-Test
#         uses: cypress-io/github-action@v2
#         with:
#           command: npm run amazon
#           browser: chrome
#           headless: true
#           record: false

# name: Workflow 3

# on:
#   workflow_dispatch:
      
#   pull_request:
 

# concurrency:
#   group: ci_workflow_group
#   cancel-in-progress: false

# jobs:
#   job1:
#     runs-on: runner2
#     steps:
#       - name: Step 1
#         run: |
#          echo "This is Workflow 3 - Job 1"
#           sleep 30 
#   job2:
#     runs-on: test2
# #    needs: job1
#     steps:
#       - name: Step 1
#         run: echo "This is Workflow 3 - Job 2"
