name: Workflow-6

on:
  workflow_dispatch:  

jobs:
  example-job2:
    runs-on: self-hosted
    steps:
      - name: Acquire lock
        id: acquire-lock
        run: |
          LOCK_FILE=/tmp/workflow.lock
          while [ -f $LOCK_FILE ]; do
            echo "Another workflow running. waiting..."
            sleep 10
          done
          touch $LOCK_FILE
      - name: Step 2
        run: |
         echo "This is Workflow 6 - Job 1"
         cat /proc/sys/kernel/hostname
      - name: Release lock
        if: always()
        run: |
          LOCK_FILE=/tmp/workflow.lock
          rm -f $LOCK_FILE
