name: Workflow 1

on:
  workflow_dispatch: # Triggered manually

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Acquire Lock
        id: acquire-lock
        run: |
          echo "Acquiring lock for Workflow 1"
          echo "lock=true" > lock.txt
      - name: Step 1
        run: echo "This is Workflow 1 - Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Step 1
        run: echo "This is Workflow 1 - Job 2"
      - name: Release Lock
        if: success()
        run: |
          echo "Releasing lock for Workflow 1"
          rm lock.txt
